version: "3"
services:
  server:
    container_name: NODEJS_SERVER_MEDIUM
    build: "."
    environment:
       - MONGO_URI=mongodb://db:27017/?compressors=zlib&gssapiServiceName=mongodb
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    depends_on:
      - db
    networks:
      - my_net
    ports:
      - "9000:9000"
    links:
      - db
    restart: on-failure
  db:
    image: "mongo"
    container_name: MONGODB_MEDIUM
    networks:
      - my_net
    volumes:
      - ./data/db:/data/db
    ports:
    - "27017:27017"
networks:
  my_net:
    driver: bridge